Repository DoodleScheduling/swagger-hub-controller, pull requests merged in 2025-01, with the labels that each got.

#141 fix: swaggerspecification readme docs / tests
  README.md
  chart/swagger-hub-controller/crds/swagger.infra.doodle.com_swaggerhubs.yaml
  config/base/crd/bases/swagger.infra.doodle.com_swaggerhubs.yaml
  config/rbac/role.yaml
  internal/controllers/suite_test.go
  internal/controllers/swaggerhub_controller_test.go
  internal/controllers/swaggerspecification_controller.go
  internal/controllers/swaggerspecification_controller_test.go
  main.go
Labels: size/L

#143 fix: rbac configmaps
  chart/swagger-hub-controller/templates/clusterrole.yaml
  config/rbac/role.yaml
  internal/controllers/swaggerhub_controller.go
Labels: size/S

#142 docs: readme changes
  README.md
Labels: size/XS

#144 fix: specification rbac /status
  chart/swagger-hub-controller/templates/clusterrole.yaml
  config/rbac/role.yaml
  internal/controllers/swaggerhub_controller.go
Labels: size/XS

#150 ci: DK-5221 update ci python version to 3.13
  .github/workflows/pr-build.yaml
Labels: size/XS
